/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package SystemFrames;
import java.io.File;
import Model.User;
import Services.Student;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.ZoneId;
import java.time.temporal.ChronoUnit;
import java.util.Date;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;


public class MainSys extends javax.swing.JFrame {

    DefaultTableModel model = new DefaultTableModel();
    
    public MainSys() {
        initComponents();
        std = new Student();
    }
    Student std = new Student();
    User user = new User();
   
    private File selectedFile;
    private void openFileChooser() {
       
        FileNameExtensionFilter filter = new FileNameExtensionFilter(
                "Image Files", "jpg", "jpeg", "png", "gif", "bmp");
        FileChooser.setFileFilter(filter);
        int result = FileChooser.showOpenDialog(this);
        if (result == FileChooser.APPROVE_OPTION) {
            selectedFile = FileChooser.getSelectedFile();          
            studImage.setText("Selected: " + selectedFile.getName());
//            String newName = selectedFile.getName().replaceFirst(studnum.toString(), "");
            
        }
    }
    private void renameFile() {
        Object newName = "";
        if (selectedFile == null) return;
            String parentPath = selectedFile.getParent();
            String extension = "";
            String fileName = selectedFile.getName();
            int dotIndex = fileName.lastIndexOf('.');
                if (dotIndex > 0 && dotIndex < fileName.length() -1) {
                    extension = fileName.substring(dotIndex);
                }
                File newFile = new File(parentPath, studnum + extension);
                if (newFile.exists()) {
                    JOptionPane.showMessageDialog(this,
                            "File with this name already exists!",
                            "Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }
                boolean success = selectedFile.renameTo(newFile);
            if (success) {
                studImage.setText("Renamed to: " + studnum.getName());
                selectedFile = newFile;
            } else {
                JOptionPane.showMessageDialog(this,
                        "Failed to rename file.",
                        "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton2 = new javax.swing.JRadioButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jFrame1 = new javax.swing.JFrame();
        FileChooser = new javax.swing.JFileChooser();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        studnum = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Lname = new javax.swing.JTextField();
        Fname = new javax.swing.JTextField();
        midinit = new javax.swing.JTextField();
        male = new javax.swing.JRadioButton();
        female = new javax.swing.JRadioButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        age = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        college = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        parent = new javax.swing.JTextField();
        contact = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        save = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        studImage = new javax.swing.JTextField();
        signImage = new javax.swing.JTextField();
        image = new javax.swing.JButton();
        sign = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        rename = new javax.swing.JButton();
        bDay = new com.toedter.calendar.JDateChooser();

        jRadioButton2.setText("jRadioButton2");

        FileChooser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FileChooserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jFrame1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(FileChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jFrame1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(FileChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 60));

        jLabel1.setText("STUDENT NO.:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 89, -1, -1));

        studnum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studnumActionPerformed(evt);
            }
        });
        studnum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                studnumKeyTyped(evt);
            }
        });
        jPanel1.add(studnum, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 112, 94, -1));

        jLabel2.setText("LASTNAME:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 140, -1, -1));

        jLabel3.setText("FIRSTNAME:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 140, -1, -1));

        jLabel4.setText("MIDDLE INITIAL:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, -1, -1));

        Lname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LnameActionPerformed(evt);
            }
        });
        Lname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                LnameKeyTyped(evt);
            }
        });
        jPanel1.add(Lname, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 162, 166, -1));

        Fname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                FnameKeyTyped(evt);
            }
        });
        jPanel1.add(Fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 162, 145, -1));

        midinit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                midinitActionPerformed(evt);
            }
        });
        midinit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                midinitKeyTyped(evt);
            }
        });
        jPanel1.add(midinit, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 160, 70, -1));

        buttonGroup1.add(male);
        male.setText("MALE");
        male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleActionPerformed(evt);
            }
        });
        jPanel1.add(male, new org.netbeans.lib.awtextra.AbsoluteConstraints(424, 163, -1, -1));

        buttonGroup1.add(female);
        female.setText("FEMALE");
        female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femaleActionPerformed(evt);
            }
        });
        jPanel1.add(female, new org.netbeans.lib.awtextra.AbsoluteConstraints(484, 163, -1, -1));

        jComboBox1.setSelectedItem(null);
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 112, 101, -1));

        jLabel5.setText("BIRTHDAY:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 193, -1, -1));

        age.setEditable(false);
        age.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ageActionPerformed(evt);
            }
        });
        age.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ageKeyTyped(evt);
            }
        });
        jPanel1.add(age, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 70, -1));

        jLabel6.setText("AGE:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 193, -1, -1));

        college.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "College of Engineering Education", "College of Computing Education", "College of Health and Science Education", "College of Hospitality Management Education", "College of Business Administration Education", "College of Accounting Education", "College of Criminal Justice Education", "College of Teacher Education", "College of Arts and Science Education" }));
        college.setSelectedItem(null);
        college.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                collegeActionPerformed(evt);
            }
        });
        jPanel1.add(college, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, 240, -1));

        jLabel7.setText("COLLEGE:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 193, -1, -1));

        jLabel8.setText("STUDENT INFORMATION:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 61, -1, -1));

        jLabel9.setText("IN CASE OF EMERGRNCY CONTACT:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, -1));

        jLabel10.setText("PARENT/GUARDIAN NAME:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 277, -1, -1));

        parent.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                parentKeyTyped(evt);
            }
        });
        jPanel1.add(parent, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 299, 217, -1));

        contact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactActionPerformed(evt);
            }
        });
        contact.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                contactKeyTyped(evt);
            }
        });
        jPanel1.add(contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(297, 299, 126, -1));

        jLabel11.setText("CONTACT NUMBER:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(297, 277, -1, -1));

        save.setText("SAVE");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        jPanel1.add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 553, 135, 30));

        cancel.setText("CANCEL");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        jPanel1.add(cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 553, 131, 30));
        jPanel1.add(studImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 142, 30));
        jPanel1.add(signImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 360, 134, 30));

        image.setText("IMAGE");
        image.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imageActionPerformed(evt);
            }
        });
        jPanel1.add(image, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 142, 30));

        sign.setText("SIGNATURE");
        jPanel1.add(sign, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 400, 130, 30));

        jLabel12.setText("STUDENT IMAGES:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 120, -1));

        rename.setText("RENAME IMAGE");
        rename.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                renameActionPerformed(evt);
            }
        });
        jPanel1.add(rename, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 443, 120, 30));

        bDay.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                bDayPropertyChange(evt);
            }
        });
        jPanel1.add(bDay, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 597, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void studnumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studnumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_studnumActionPerformed

    private void maleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maleActionPerformed

    private void femaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_femaleActionPerformed

    private void ageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ageActionPerformed

    private void contactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contactActionPerformed

    public void fieldEraser(){
        
    }
    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
//        SysTable STable = new SysTable();
//        //Gendah
        try {
        String genders = "";
        if(male.isSelected()){
            genders = "Male";                   
        }else if(female.isSelected()){
            genders = "Female";
        }

        int reply = JOptionPane.showConfirmDialog(this, "Confirm Submission", "Confirmation", JOptionPane.YES_NO_OPTION);
            java.sql.Date sqlDate = new java.sql.Date(bDay.getTime());
            if (reply == JOptionPane.YES_OPTION) { 
                try {
//                    user = new User(WIDTH, genders, genders, genders, genders, college, date)
                    user.setID(Integer.parseInt(studnum.getText()));
                    user.setFname(Lname.getText());
                    user.setMname(Fname.getText());
                    user.setLname(midinit.getText());
                    user.setCollege(college.getSelectedItem());
                    user.setGender(genders);
                    user.setDate(sqlDate);
                    user.setAge(Integer.parseInt(age.getText()));

                    studnum.setText("");
                    Lname.setText("");
                    Fname.setText("");
                    midinit.setText("");
                    age.setText(null);
                    college.setSelectedItem(null);
                    buttonGroup1.clearSelection();
                    contact.setText("");    
                    bDay.setDate(null);
                    std.addStudent(user); 
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, e.getMessage());
                    System.out.println(e);
                }
            }else{
                JOptionPane.showMessageDialog(null, "Ok you change your mind");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
            System.out.println(e);
        }
    }//GEN-LAST:event_saveActionPerformed

    private void LnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LnameActionPerformed
        
    }//GEN-LAST:event_LnameActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        studnum.setText("");
        Lname.setText("");
        Fname.setText("");
        midinit.setText("");
        buttonGroup1.clearSelection();
        contact.setText("");    
        bDay.setDate(null);
        dispose();
    }//GEN-LAST:event_cancelActionPerformed

    private void collegeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_collegeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_collegeActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void studnumKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_studnumKeyTyped
        char charac = evt.getKeyChar();
       if (!Character.isDigit(charac)){
           evt.consume();
           
       }else{
       }
    }//GEN-LAST:event_studnumKeyTyped

    private void ageKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ageKeyTyped
        char charac = evt.getKeyChar();
       if (!Character.isDigit(charac)){
           evt.consume();
           
       }else{
       }
    }//GEN-LAST:event_ageKeyTyped

    private void contactKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_contactKeyTyped
        char charac = evt.getKeyChar();
       if (!Character.isDigit(charac)){
           evt.consume();
           
       }else{
       }
    }//GEN-LAST:event_contactKeyTyped

    private void LnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_LnameKeyTyped
        String text = Lname.getText();
        char charac = evt.getKeyChar();
       if (!Character.isAlphabetic(charac) && charac != ' ') {
       evt.consume();
       text.toUpperCase();
       }else{
       }    
       
    }//GEN-LAST:event_LnameKeyTyped

    private void FnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FnameKeyTyped
        char charac = evt.getKeyChar();
       if (!Character.isAlphabetic(charac) && charac != ' ') {
       evt.consume();
       }else{
       }    
    }//GEN-LAST:event_FnameKeyTyped

    private void midinitKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_midinitKeyTyped
        char charac = evt.getKeyChar();
       if (!Character.isAlphabetic(charac) ) {
       evt.consume();
       }else{
       }    
    }//GEN-LAST:event_midinitKeyTyped

    private void parentKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_parentKeyTyped
        char charac = evt.getKeyChar();
       if (!Character.isAlphabetic(charac) && charac != ' ' && charac != '.') {
       evt.consume();
       }else{
       }    
    }//GEN-LAST:event_parentKeyTyped

    private void imageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imageActionPerformed
        openFileChooser();
//            jFrame1.setSize(800,500);
//        jFrame1.setVisible(true);
//            FileNameExtensionFilter filter = new FileNameExtensionFilter(
//                "Image Files", "jpg", "jpeg", "png", "gif", "bmp");
//            
//            JFileChooser fc = new JFileChooser();
//            fc.setFileFilter(filter);
//            fc.setDialogTitle("Select Image");
//            fc.setCurrentDirectory(new java.io.File("I:/Gallery"));
//            fc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
//                if(fc.showOpenDialog(image) == JFileChooser.APPROVE_OPTION){
//                    studImage.setText(fc.getSelectedFile().getAbsolutePath());
//                }else{
//
//                }
            
    }//GEN-LAST:event_imageActionPerformed

    private void FileChooserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FileChooserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FileChooserActionPerformed

    private void renameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_renameActionPerformed
       renameFile();
    }//GEN-LAST:event_renameActionPerformed

    private void midinitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_midinitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_midinitActionPerformed

    private void bDayPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_bDayPropertyChange
        if ("date".equals(evt.getPropertyName())) {
                    java.util.Date selectedDate = bDay.getDate();
                    if (selectedDate != null) {
                        int edad = calculateAge(selectedDate);
                        age.setText(String.valueOf(edad));
                    } else {
                        
                    }
                }
    }//GEN-LAST:event_bDayPropertyChange
    private int calculateAge(Date birthDate) {
        LocalDate birthLocalDate = birthDate.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        LocalDate today = LocalDate.now();
        if (birthLocalDate.isAfter(today)) {
            return 0;
        }
        return (int) ChronoUnit.YEARS.between(birthLocalDate, today);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainSys.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainSys.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainSys.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainSys.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainSys().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser FileChooser;
    private javax.swing.JTextField Fname;
    private javax.swing.JTextField Lname;
    private javax.swing.JTextField age;
    private com.toedter.calendar.JDateChooser bDay;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton cancel;
    private javax.swing.JComboBox<String> college;
    private javax.swing.JTextField contact;
    private javax.swing.JRadioButton female;
    private javax.swing.JButton image;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton male;
    private javax.swing.JTextField midinit;
    private javax.swing.JTextField parent;
    private javax.swing.JButton rename;
    private javax.swing.JButton save;
    private javax.swing.JButton sign;
    private javax.swing.JTextField signImage;
    private javax.swing.JTextField studImage;
    private javax.swing.JTextField studnum;
    // End of variables declaration//GEN-END:variables
}
