package SystemFrames;

import Services.Student;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.YES_NO_OPTION;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;


public class SysTable extends javax.swing.JFrame {

    DefaultTableModel model = new DefaultTableModel();
    private Student std;
    public SysTable() {
        initComponents();
        std = new Student();
        populatedTable();
    }
    public void populatedTable(){
        DefaultTableModel model = (DefaultTableModel)IDTable.getModel();
        std.populateTable(model);
        
    }
    public void addRow(Object[] rowData) {
        model = (DefaultTableModel) IDTable.getModel();
        model.addRow(rowData);
        }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        IDTable = new javax.swing.JTable();
        delete = new javax.swing.JButton();
        edit = new javax.swing.JButton();
        searchBar = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        request = new javax.swing.JButton();
        newId = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1228, 80));

        IDTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID NO.", "LAST NAME", "FIRST NAME", "M.I.", "COLLEGE", "GENDER"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        IDTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IDTableMouseClicked(evt);
            }
        });
        IDTable.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                IDTableKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(IDTable);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 139, 1153, 487));

        delete.setText("DELETE");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        jPanel1.add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(1057, 638, 106, -1));

        edit.setText("UPDATE");
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });
        jPanel1.add(edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 640, 108, -1));

        searchBar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBarActionPerformed(evt);
            }
        });
        searchBar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchBarKeyReleased(evt);
            }
        });
        jPanel1.add(searchBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 208, 30));

        jLabel1.setText("SEARCH");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        request.setText("REQUEST ID");
        request.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestActionPerformed(evt);
            }
        });
        jPanel1.add(request, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 90, 120, 40));

        newId.setText("NEW ID");
        newId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newIdActionPerformed(evt);
            }
        });
        jPanel1.add(newId, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 90, 115, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 678, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
//        UpdateFrame IDReg = new UpdateFrame();
//        IDReg.setVisible(true);
//        dispose();
        
    }//GEN-LAST:event_editActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        model = (DefaultTableModel) IDTable.getModel();
        if (IDTable.getSelectedRowCount() == 1){
            int confirm  = JOptionPane.showConfirmDialog(this, "Delete Confirmation", "Please Confirm",YES_NO_OPTION);
            if (confirm == JOptionPane.YES_OPTION){
                model.removeRow(IDTable.getSelectedRow());
                JOptionPane.showMessageDialog(this, "Deleted Successfully");
            }else {
                JOptionPane.showMessageDialog(this, "Delete Canceled"); 
            }
        }else{
            if (IDTable.getRowCount() == 0){
                JOptionPane.showMessageDialog(this, "Table is Empty");
            }else {
                JOptionPane.showMessageDialog(this, "No Row Selected");
            }
        }
        
    }//GEN-LAST:event_deleteActionPerformed

    private void searchBarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchBarActionPerformed

    private void searchBarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchBarKeyReleased
        DefaultTableModel model = (DefaultTableModel) IDTable.getModel();
        TableRowSorter<DefaultTableModel> obj = new TableRowSorter<>(model);
        IDTable.setRowSorter(obj);
        obj.setRowFilter(RowFilter.regexFilter(searchBar.getText())); 
       
    }//GEN-LAST:event_searchBarKeyReleased

    private void requestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestActionPerformed
        IDReq id = new IDReq();
        id.setVisible(true);
        dispose();
    }//GEN-LAST:event_requestActionPerformed

    private void newIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newIdActionPerformed
        MainSys IDReg = new MainSys();
        IDReg.setVisible(true);
        dispose();
    }//GEN-LAST:event_newIdActionPerformed

    private void IDTableKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_IDTableKeyTyped
        
    }//GEN-LAST:event_IDTableKeyTyped

    private void IDTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IDTableMouseClicked
        try {
            UpdateFrame otherFrame = new UpdateFrame();
            int row = IDTable.getSelectedRow();
                int column = IDTable.getSelectedColumn();
                if (row >= 0) {
                    int id = (int) IDTable.getValueAt(row, 0); 
                    String lname = (String) IDTable.getValueAt(row, 1);
                    String fname = (String) IDTable.getValueAt(row, 2);
                    String mname = (String) IDTable.getValueAt(row, 3);
                    Object college = (Object) IDTable.getValueAt(row, 4);
                    String gender = (String) IDTable.getValueAt(row, 5);
                    otherFrame.setID(id);
                    otherFrame.setLname(lname);
                    otherFrame.setFname(fname);
                    otherFrame.setMname(mname);
                    otherFrame.setCollege(college);
                    otherFrame.setGender(gender);
                    otherFrame.setVisible(true);
                }
            
            dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
            
    }//GEN-LAST:event_IDTableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SysTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SysTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SysTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SysTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SysTable().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable IDTable;
    private javax.swing.JButton delete;
    private javax.swing.JButton edit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton newId;
    private javax.swing.JButton request;
    private javax.swing.JTextField searchBar;
    // End of variables declaration//GEN-END:variables
}
