/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package SystemFrames;
import java.io.File;
import Model.User;
import Services.Student;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.ZoneId;
import java.time.temporal.ChronoUnit;
import java.util.Date;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

public class UpdateFrame extends javax.swing.JFrame {

    DefaultTableModel model = new DefaultTableModel();
    
    public UpdateFrame() {
        initComponents();
        std = new Student();
    }
    Student std = new Student();
    User user = new User();
    PreparedStatement ps;
    String sql;
    Connection connection;
    
//    private File selectedFile;
//    private void openFileChooser() {
//       
//        FileNameExtensionFilter filter = new FileNameExtensionFilter(
//                "Image Files", "jpg", "jpeg", "png", "gif", "bmp");
//        FileChooser.setFileFilter(filter);
//        int result = FileChooser.showOpenDialog(this);
//        if (result == FileChooser.APPROVE_OPTION) {
//            selectedFile = FileChooser.getSelectedFile();          
//            studImage.setText("Selected: " + selectedFile.getName());
////            String newName = selectedFile.getName().replaceFirst(studnum.toString(), "")
    /// @param id;
//            
//        }
//    }
//    private void renameFile() {
//        Object newName = "";
//        if (selectedFile == null) return;
//            String parentPath = selectedFile.getParent();
//            String extension = "";
//            String fileName = selectedFile.getName();
//            int dotIndex = fileName.lastIndexOf('.');
//                if (dotIndex > 0 && dotIndex < fileName.length() -1) {
//                    extension = fileName.substring(dotIndex);
//                }
//                File newFile = new File(parentPath, studnum + extension);
//                if (newFile.exists()) {
//                    JOptionPane.showMessageDialog(this,
//                            "File with this name already exists!",
//                            "Error", JOptionPane.ERROR_MESSAGE);
//                    return;
//                }
//                boolean success = selectedFile.renameTo(newFile);
//            if (success) {
//                studImage.setText("Renamed to: " + studnum.getName());
//                selectedFile = newFile;
//            } else {
//                JOptionPane.showMessageDialog(this,
//                        "Failed to rename file.",
//                        "Error", JOptionPane.ERROR_MESSAGE);
//        }
//    }
    public void setID(int id) {
        studnum.setText(String.valueOf(id));
    }
    public void setFname(String fname) {
        Fname.setText(fname);
    }
    public void setMname(String mname) {
        midinit.setText(mname);
    }
    public void setLname(String lname) {
        Lname.setText(lname);
    }
    public void setCollege(Object collegebox) {
        college.setSelectedItem(collegebox);
    }
    public void setGender (String gender){
        try {
            gender = "";
        if ("Male".equals(gender)) {
                male.setSelected(true);                  
            } else if ("Female".equals(gender)) {
                female.setSelected(true); 
        }
        } catch (Exception e) {
            e.printStackTrace();
        }     
        }
        public void setDate (Date bdate){
            bDay.setDate(bdate);
        }
        public void setAge (int edad){
            age.setText(String.valueOf(edad));
        }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton2 = new javax.swing.JRadioButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jFrame1 = new javax.swing.JFrame();
        FileChooser = new javax.swing.JFileChooser();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        studnum = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Lname = new javax.swing.JTextField();
        Fname = new javax.swing.JTextField();
        midinit = new javax.swing.JTextField();
        male = new javax.swing.JRadioButton();
        female = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        age = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        college = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        save = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        bDay = new com.toedter.calendar.JDateChooser();
        jLabel9 = new javax.swing.JLabel();

        jRadioButton2.setText("jRadioButton2");

        FileChooser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FileChooserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jFrame1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(FileChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jFrame1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(FileChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 102, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 60));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel1.setText("STUDENT NO.:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 89, -1, -1));

        studnum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studnumActionPerformed(evt);
            }
        });
        studnum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                studnumKeyTyped(evt);
            }
        });
        jPanel1.add(studnum, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 112, 94, -1));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel2.setText("LASTNAME:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 140, -1, -1));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel3.setText("FIRSTNAME:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 140, -1, -1));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel4.setText("MIDDLE INITIAL:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 140, -1, -1));

        Lname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LnameActionPerformed(evt);
            }
        });
        Lname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                LnameKeyTyped(evt);
            }
        });
        jPanel1.add(Lname, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 162, 166, -1));

        Fname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                FnameKeyTyped(evt);
            }
        });
        jPanel1.add(Fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 162, 145, -1));

        midinit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                midinitActionPerformed(evt);
            }
        });
        midinit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                midinitKeyTyped(evt);
            }
        });
        jPanel1.add(midinit, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 160, 70, 20));

        buttonGroup1.add(male);
        male.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        male.setText("MALE");
        male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleActionPerformed(evt);
            }
        });
        jPanel1.add(male, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 230, -1, -1));

        buttonGroup1.add(female);
        female.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        female.setText("FEMALE");
        female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femaleActionPerformed(evt);
            }
        });
        jPanel1.add(female, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 230, -1, -1));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel5.setText("BIRTHDATE:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        age.setEditable(false);
        age.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ageActionPerformed(evt);
            }
        });
        age.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ageKeyTyped(evt);
            }
        });
        jPanel1.add(age, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, 70, -1));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel6.setText("AGE:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, -1, -1));

        college.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "College of Engineering Education", "College of Computing Education", "College of Health and Science Education", "College of Hospitality Management Education", "College of Business Administration Education", "College of Accounting Education", "College of Criminal Justice Education", "College of Teacher Education", "College of Arts and Science Education" }));
        college.setSelectedItem(null);
        college.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                collegeActionPerformed(evt);
            }
        });
        jPanel1.add(college, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 240, -1));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel7.setText("COLLEGE/ PROGRAM:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, -1));

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel8.setText("STUDENT INFORMATION");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, -1, -1));

        save.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        save.setText("SAVE");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        jPanel1.add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 360, 110, 30));

        cancel.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        cancel.setText("CANCEL");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        jPanel1.add(cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 360, 110, 30));

        bDay.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                bDayPropertyChange(evt);
            }
        });
        jPanel1.add(bDay, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 120, -1));

        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel9.setText("GENDER:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    private void studnumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studnumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_studnumActionPerformed

    private void maleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maleActionPerformed

    private void femaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_femaleActionPerformed

    private void ageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ageActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        user.setID(Integer.parseInt(studnum.getText()));
        int ID = Integer.parseInt(studnum.getText());             

        try {
            if (connection != null){
            sql = "SELECT * FROM `id_registry` WHERE studid=? ";
            ps = connection.prepareStatement(sql);
            ps.setInt(1, ID);
            ps.executeQuery();
           
           std.Update(user);
 
            }else{
                JOptionPane.showMessageDialog(this, "ïs null");
            }
           
        } catch (Exception e) {
        JOptionPane.showMessageDialog(this, e.getMessage());
        System.out.println(e);
        }    
//        try {
//        String genders = "";
//        if (male.isSelected()) {
//            genders = "Male";                   
//        } else if (female.isSelected()) {
//            genders = "Female";
//        }
//        int reply = JOptionPane.showConfirmDialog(this, "Confirm Submission",
//                "Confirmation", JOptionPane.YES_NO_OPTION);
//        
//        java.util.Date utilDate = bDay.getDate(); 
//        java.sql.Date sqlDate = null;
//        
//        if (utilDate != null) {
//            sqlDate = new java.sql.Date(utilDate.getTime());
//        } else {
//            JOptionPane.showMessageDialog(this, "Please select a valid birth date.");
//            return; 
//        }
//        if (reply == JOptionPane.YES_OPTION) { 
//            try {   
//                String updateQuery = "UPDATE `ìd_registry` SET lastname = ?, firstname = ?, midinitial = ?, college = ?, gender = ?, birthdi= ?, age = ? WHERE student_id = ?";
//                ps= connection.prepareStatement(updateQuery);
//                
//                ps.setString(1, Lname.getText());
//                ps.setString(2, Fname.getText());
//                ps.setString(3, midinit.getText());
//                ps.setString(4, college.getSelectedItem().toString());
//                ps.setString(5, genders);
//                ps.setDate(6, sqlDate);
//                ps.setInt(7, Integer.parseInt(age.getText()));
//                int result = ps.executeUpdate();
//                
//                if (result > 0) { 
//                    JOptionPane.showMessageDialog(this, "Update Successful");
//                } else {
//                    JOptionPane.showMessageDialog(this, "Failed to Update");
//                }
//                // Clear form fields
//                studnum.setText("");
//                Lname.setText("");
//                Fname.setText("");
//                midinit.setText("");
//                age.setText(null);
//                college.setSelectedItem(null);
//                bDay.setDate(null);
//                
//                
//            } catch (Exception e) {
//                JOptionPane.showMessageDialog(this, e.getMessage());
//                System.out.println(e);
//            }
//        } else {
//            JOptionPane.showMessageDialog(null, "Ok you changed your mind");
        
    
        
    
//        try {
//            user.setID(Integer.parseInt(studnum.getText()));
//            int ID = Integer.parseInt(studnum.getText());  
//            java.util.Date utilDate = bDay.getDate(); 
//            java.sql.Date sqlDate = null;
//                        
//        try {
//            String genders = "";
//        if(male.isSelected()){
//            genders = "Male";                   
//        }else if(female.isSelected()){
//            genders = "Female";
//        }
////            
////            user.setID(Integer.parseInt(studnum.getText()));
////            user.setFname(Lname.getText());
////            user.setMname(Fname.getText());
////            user.setLname(midinit.getText());
////            user.setCollege(college.getSelectedItem());
////            user.setGender(genders);
////            user.setDate(sqlDate);
////            user.setAge(Integer.parseInt(age.getText()));
//
//            sql = "SELECT * FROM `id_registry` WHERE studid=? ";
//            ps = connection.prepareStatement(sql);           
//            ps.setInt(1, ID);
//            ps.executeQuery();
//            std.Update(user);
//            } catch (Exception e) {
//                    JOptionPane.showMessageDialog(this, e.getMessage());
//                    System.out.println(e);
//            }         
//}
//        catch (Exception e) {
//            JOptionPane.showMessageDialog(this, e.getMessage());
//        }
//        
    }//GEN-LAST:event_saveActionPerformed
    
    private void LnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LnameActionPerformed
        
    }//GEN-LAST:event_LnameActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        studnum.setText("");
        Lname.setText("");
        Fname.setText("");
        midinit.setText("");
        buttonGroup1.clearSelection();        
        bDay.setDate(null);
        dispose();
    }//GEN-LAST:event_cancelActionPerformed

    private void collegeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_collegeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_collegeActionPerformed

    private void studnumKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_studnumKeyTyped
        char charac = evt.getKeyChar();
       if (!Character.isDigit(charac)){
           evt.consume();
           
       }else{
       }
    }//GEN-LAST:event_studnumKeyTyped

    private void ageKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ageKeyTyped
        char charac = evt.getKeyChar();
       if (!Character.isDigit(charac)){
           evt.consume();
           
       }else{
       }
    }//GEN-LAST:event_ageKeyTyped

    private void LnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_LnameKeyTyped
        String text = Lname.getText();
        char charac = evt.getKeyChar();
       if (!Character.isAlphabetic(charac) && charac != ' ') {
       evt.consume();
       text.toUpperCase();
       
     
       }else{
       }    
       
    }//GEN-LAST:event_LnameKeyTyped

    private void FnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FnameKeyTyped
        char charac = evt.getKeyChar();
       if (!Character.isAlphabetic(charac) && charac != ' ') {
       evt.consume();
       }else{
       }    
    }//GEN-LAST:event_FnameKeyTyped

    private void midinitKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_midinitKeyTyped
        char charac = evt.getKeyChar();
       if (!Character.isAlphabetic(charac) ) {
       evt.consume();
       }else{
       }    
    }//GEN-LAST:event_midinitKeyTyped

    private void FileChooserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FileChooserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FileChooserActionPerformed

    private void midinitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_midinitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_midinitActionPerformed

    private void bDayPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_bDayPropertyChange
        if ("date".equals(evt.getPropertyName())) {
                    Date selectedDate = bDay.getDate();
                    if (selectedDate != null) {
                        int edad = calculateAge(selectedDate);
                        age.setText(String.valueOf(edad));
                    } else {
                        
                    }
                }
    }//GEN-LAST:event_bDayPropertyChange
    private int calculateAge(Date birthDate) {
        LocalDate birthLocalDate = birthDate.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        LocalDate today = LocalDate.now();
        if (birthLocalDate.isAfter(today)) {
            return 0;
        }
        return (int) ChronoUnit.YEARS.between(birthLocalDate, today);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateFrame().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser FileChooser;
    private javax.swing.JTextField Fname;
    private javax.swing.JTextField Lname;
    private javax.swing.JTextField age;
    private com.toedter.calendar.JDateChooser bDay;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton cancel;
    private javax.swing.JComboBox<String> college;
    private javax.swing.JRadioButton female;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton male;
    private javax.swing.JTextField midinit;
    private javax.swing.JButton save;
    private javax.swing.JTextField studnum;
    // End of variables declaration//GEN-END:variables
}
