package Controller;
import Model.User;
import Services.Student;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.PreparedStatement;



public class AttendanceMonitor extends javax.swing.JFrame {

    Student std = new Student();
    User user = new User();
    Connection connection ;
    ResultSet rs;
    PreparedStatement ps;
    String sql;
    public AttendanceMonitor() {       
        initComponents();
        
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */ 
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Id = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        name2 = new javax.swing.JTextField();
        NAME = new javax.swing.JLabel();
        LogOutBtn = new javax.swing.JButton();
        ViewBtn = new javax.swing.JButton();
        name1 = new javax.swing.JTextField();
        NAME1 = new javax.swing.JLabel();
        name3 = new javax.swing.JTextField();
        NAME2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        LogInBtn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(500, 250));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Id.setBackground(new java.awt.Color(0, 0, 0));
        Id.setForeground(new java.awt.Color(255, 255, 255));
        Id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IdActionPerformed(evt);
            }
        });
        getContentPane().add(Id, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 58, -1));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ID Number");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        name2.setBackground(new java.awt.Color(0, 0, 0));
        name2.setForeground(new java.awt.Color(255, 255, 255));
        name2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name2ActionPerformed(evt);
            }
        });
        getContentPane().add(name2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 150, -1));

        NAME.setBackground(new java.awt.Color(255, 255, 255));
        NAME.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        NAME.setForeground(new java.awt.Color(255, 255, 255));
        NAME.setText("First Name");
        getContentPane().add(NAME, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        LogOutBtn.setBackground(new java.awt.Color(0, 0, 0));
        LogOutBtn.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        LogOutBtn.setForeground(new java.awt.Color(255, 255, 255));
        LogOutBtn.setText("LOG OUT");
        LogOutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogOutBtnActionPerformed(evt);
            }
        });
        getContentPane().add(LogOutBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 300, 150, 50));

        ViewBtn.setBackground(new java.awt.Color(0, 0, 0));
        ViewBtn.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        ViewBtn.setForeground(new java.awt.Color(255, 255, 255));
        ViewBtn.setText("ATTENDANCE MONITOR");
        ViewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewBtnActionPerformed(evt);
            }
        });
        getContentPane().add(ViewBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, 230, 50));

        name1.setBackground(new java.awt.Color(0, 0, 0));
        name1.setForeground(new java.awt.Color(255, 255, 255));
        name1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name1ActionPerformed(evt);
            }
        });
        getContentPane().add(name1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 150, -1));

        NAME1.setBackground(new java.awt.Color(255, 255, 255));
        NAME1.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        NAME1.setForeground(new java.awt.Color(255, 255, 255));
        NAME1.setText("Middle Name");
        getContentPane().add(NAME1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        name3.setBackground(new java.awt.Color(0, 0, 0));
        name3.setForeground(new java.awt.Color(255, 255, 255));
        name3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name3ActionPerformed(evt);
            }
        });
        getContentPane().add(name3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 150, -1));

        NAME2.setBackground(new java.awt.Color(255, 255, 255));
        NAME2.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        NAME2.setForeground(new java.awt.Color(255, 255, 255));
        NAME2.setText("Last Name");
        getContentPane().add(NAME2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ATTENDANCE LOGIN  ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        LogInBtn.setBackground(new java.awt.Color(0, 0, 0));
        LogInBtn.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        LogInBtn.setForeground(new java.awt.Color(255, 255, 255));
        LogInBtn.setText("LOG IN");
        LogInBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogInBtnActionPerformed(evt);
            }
        });
        getContentPane().add(LogInBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 299, 150, 50));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IdActionPerformed
        
    }//GEN-LAST:event_IdActionPerformed

    private void name2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_name2ActionPerformed
        
    }//GEN-LAST:event_name2ActionPerformed

    private void LogOutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogOutBtnActionPerformed
        try{  
            String ID = Id.getText();
            sql = "SELECT logout=? FROM attendance WHERE id=?";
            ps = connection.prepareStatement(sql);
            ps.setInt(1,Integer.parseInt(ID));            
            ps.executeQuery();
            std.logOutTime(user);
        }catch (Exception e){
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_LogOutBtnActionPerformed

    private void LogInBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogInBtnActionPerformed
        try{
             
                user.setID(Integer.parseInt(Id.getText()));
                user.setFname(name1.getText());
                user.setMname(name2.getText());
                user.setLname(name3.getText());
                       Id.setText("");
                       name1.setText("");
                       name2.setText("");
                       name3.setText("");
                std.addStudent(user);
                      
            
            
        }catch (Exception e){
            
        }  

    }//GEN-LAST:event_LogInBtnActionPerformed

    private void ViewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewBtnActionPerformed
        Monitor mon = new Monitor();
        mon.setVisible(true);
    }//GEN-LAST:event_ViewBtnActionPerformed

    private void name1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_name1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_name1ActionPerformed

    private void name3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_name3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_name3ActionPerformed

    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AttendanceMonitor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AttendanceMonitor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AttendanceMonitor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AttendanceMonitor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AttendanceMonitor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Id;
    private javax.swing.JButton LogInBtn;
    private javax.swing.JButton LogOutBtn;
    private javax.swing.JLabel NAME;
    private javax.swing.JLabel NAME1;
    private javax.swing.JLabel NAME2;
    private javax.swing.JButton ViewBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField name1;
    private javax.swing.JTextField name2;
    private javax.swing.JTextField name3;
    // End of variables declaration//GEN-END:variables

    

    
}
